spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test-seap
  jpa:
    show-sql: true
    generate-ddl: true
server:
  port: 8090
